version: '3.8'
services:
  reverse-proxy:
    image: nginx:latest
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - tds_api
      - frontend

  tds_api:
    build:
      context: ./tds_api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MYSQL_DATABASE=yourdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=database
      - MYSQL_PORT=3306
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: ./src/Dockerfile
    ports:
      - "3000:3000"

  database:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TDS
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql/

volumes:
  db-data:
