version: '3.8'
services:
  reverse-proxy:
    image: nginx:latest
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
#      - backend
      - frontend

#  backend:
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
#    ports:
#      - "5000:5000"
#    environment:
#      - DATABASE_URL=mysql://user:password@database:3306/yourdb
#    depends_on:
#      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: ./src/Dockerfile
    ports:
      - "3000:3000"

  database:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: yourdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql/

volumes:
  db-data: